version: '3.8'

services:
  configuration-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    image: configuration-service:local
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - APP_PORT=8080
      - CCF_DB_DRIVER=postgres
      - CCF_DB_CONNECTION=host=postgres user=postgres password=postgres dbname=ccf port=5432 sslmode=disable
    networks:
      - continuous-compliance

  postgres:
    image: postgres:17.5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ccf
    networks:
      - continuous-compliance

networks:
  continuous-compliance:

volumes:
  postgres:
