package authz

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	yaml "gopkg.in/yaml.v2"
)

// ExportFormat is a target the manifest vocabulary can be rendered into for GitOps
// pipelines and engines without an admin API (parent design §3.4). All formats export the
// VOCABULARY (subjects, resources, actions, attributes, roles) — not operator policies.
type ExportFormat string

const (
	// ExportJSON renders the manifest as indented JSON.
	ExportJSON ExportFormat = "json"
	// ExportYAML renders the manifest as YAML (a normalized round-trip of the source).
	ExportYAML ExportFormat = "yaml"
	// ExportCedar renders a Cedar schema (entity + action shapes) for the embedded/external
	// Cedar engines. uuid maps to String and map<string,string> to Set<String>, since Cedar
	// has no native equivalents.
	ExportCedar ExportFormat = "cedar"
	// ExportOpenFGA renders an OpenFGA authorization model (a type per resource with a
	// relation per action, directly assignable to the subject types).
	ExportOpenFGA ExportFormat = "openfga"
)

// SupportedExportFormats lists the formats Export accepts, for CLI help and validation.
var SupportedExportFormats = []ExportFormat{ExportJSON, ExportYAML, ExportCedar, ExportOpenFGA}

// ParseExportFormat maps a (case-insensitive) string to an ExportFormat.
func ParseExportFormat(s string) (ExportFormat, error) {
	switch ExportFormat(strings.ToLower(strings.TrimSpace(s))) {
	case ExportJSON:
		return ExportJSON, nil
	case ExportYAML:
		return ExportYAML, nil
	case ExportCedar:
		return ExportCedar, nil
	case ExportOpenFGA:
		return ExportOpenFGA, nil
	default:
		names := make([]string, len(SupportedExportFormats))
		for i, f := range SupportedExportFormats {
			names[i] = string(f)
		}
		return "", fmt.Errorf("authz: unknown export format %q (want one of %s)", s, strings.Join(names, ", "))
	}
}

// Export renders the manifest into the requested format.
func (m *Manifest) Export(format ExportFormat) ([]byte, error) {
	switch format {
	case ExportJSON:
		b, err := json.MarshalIndent(m, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("authz: export json: %w", err)
		}
		return append(b, '\n'), nil
	case ExportYAML:
		b, err := yaml.Marshal(m)
		if err != nil {
			return nil, fmt.Errorf("authz: export yaml: %w", err)
		}
		return b, nil
	case ExportCedar:
		return []byte(m.exportCedar()), nil
	case ExportOpenFGA:
		return []byte(m.exportOpenFGA()), nil
	default:
		return nil, fmt.Errorf("authz: unsupported export format %q", format)
	}
}

// sortedKeys returns the keys of a string-keyed map in deterministic order, so every export
// is byte-stable for diff-friendly GitOps.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// entityNames returns the union of subject and resource names, sorted. A name that is both
// a subject and a resource (user, agent) is a single entity: it can act as a principal and
// be acted upon, so it is emitted once with the union of both attribute sets.
func (m *Manifest) entityNames() []string {
	set := map[string]struct{}{}
	for name := range m.Subjects {
		set[name] = struct{}{}
	}
	for name := range m.Resources {
		set[name] = struct{}{}
	}
	return sortedKeys(set)
}

// mergedAttrs unions a name's subject and resource attributes (disjoint in practice — e.g.
// principal auth_method vs the user record's is_active), so the single entity carries both.
func (m *Manifest) mergedAttrs(name string) map[string]string {
	out := map[string]string{}
	if s, ok := m.Subjects[name]; ok {
		for k, v := range s.Attributes {
			out[k] = v
		}
	}
	if r, ok := m.Resources[name]; ok {
		for k, v := range r.Attributes {
			out[k] = v
		}
	}
	return out
}

// exportCedar renders the vocabulary as a Cedar schema: one entity per subject/resource
// name (deduped, so user/agent — both a subject and a resource — appear once with the union
// of their attributes), and an action declaration per action listing the resource types it
// applies to. It is the schema, not policies.
func (m *Manifest) exportCedar() string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by `ccf authz export --format=cedar` — CCF authz vocabulary (schemaVersion %d).\n", m.SchemaVersion)
	b.WriteString("// This is the authorization SCHEMA (entity + action shapes), not policies.\n")
	b.WriteString("// uuid -> String and map<string,string> -> Set<String> (Cedar has no native equivalents).\n\n")
	b.WriteString("namespace CCF {\n")

	// One entity per name (subjects ∪ resources), with the union of its attributes.
	for _, name := range m.entityNames() {
		writeCedarEntity(&b, name, m.mergedAttrs(name))
	}

	// Actions: name -> set of resource types it applies to. Principals are every subject type.
	principals := make([]string, 0, len(m.Subjects))
	for _, name := range sortedKeys(m.Subjects) {
		principals = append(principals, cedarEntityName(name))
	}
	actionResources := map[string]map[string]struct{}{}
	for _, res := range sortedKeys(m.Resources) {
		for _, action := range m.Resources[res].Actions {
			if actionResources[action] == nil {
				actionResources[action] = map[string]struct{}{}
			}
			actionResources[action][cedarEntityName(res)] = struct{}{}
		}
	}
	for _, action := range sortedKeys(actionResources) {
		resources := sortedKeys(actionResources[action])
		fmt.Fprintf(&b, "\n  action \"%s\" appliesTo {\n", action)
		fmt.Fprintf(&b, "    principal: [%s],\n", strings.Join(principals, ", "))
		fmt.Fprintf(&b, "    resource: [%s]\n  };\n", strings.Join(resources, ", "))
	}

	b.WriteString("}\n")
	return b.String()
}

func writeCedarEntity(b *strings.Builder, name string, attrs map[string]string) {
	entity := cedarEntityName(name)
	if len(attrs) == 0 {
		fmt.Fprintf(b, "  entity %s;\n", entity)
		return
	}
	fmt.Fprintf(b, "  entity %s {\n", entity)
	for _, attr := range sortedKeys(attrs) {
		fmt.Fprintf(b, "    %s: %s,\n", attr, cedarType(attrs[attr]))
	}
	b.WriteString("  };\n")
}

// cedarType maps a manifest attribute type onto a Cedar type.
func cedarType(t string) string {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case "bool":
		return "Bool"
	case "set<string>", "map<string,string>":
		return "Set<String>"
	default: // string, uuid, and anything else
		return "String"
	}
}

// cedarEntityName converts a manifest resource/subject name into a PascalCase Cedar entity
// type name (component-definition -> ComponentDefinition, poam_oscal -> PoamOscal).
func cedarEntityName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '-' || r == '_' || r == '.' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// exportOpenFGA renders the vocabulary as an OpenFGA authorization model (DSL): one type
// per subject/resource name (deduped), where a resource type's relations are its actions,
// each directly assignable to every subject type. Subject-only types carry no relations.
func (m *Manifest) exportOpenFGA() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `ccf authz export --format=openfga` — CCF authz vocabulary (schemaVersion %d).\n", m.SchemaVersion)
	b.WriteString("model\n  schema 1.1\n")

	subjectTypes := make([]string, 0, len(m.Subjects))
	for _, name := range sortedKeys(m.Subjects) {
		subjectTypes = append(subjectTypes, ofgaName(name))
	}
	assignable := "[" + strings.Join(subjectTypes, ", ") + "]"

	for _, name := range m.entityNames() {
		fmt.Fprintf(&b, "\ntype %s\n", ofgaName(name))
		res, ok := m.Resources[name]
		if !ok {
			continue // subject-only type (no relations)
		}
		actions := append([]string(nil), res.Actions...)
		sort.Strings(actions)
		if len(actions) > 0 {
			b.WriteString("  relations\n")
		}
		for _, action := range actions {
			fmt.Fprintf(&b, "    define %s: %s\n", ofgaName(action), assignable)
		}
	}
	return b.String()
}

// ofgaName sanitizes a manifest name into an OpenFGA type/relation identifier (letters,
// digits and underscore only): component-definition -> component_definition,
// users.manage -> users_manage.
func ofgaName(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}
