{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ccf-api.fullname" . }}-network-policy
  labels:
    {{- include "ccf-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ccf-api.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from API pods to PostgreSQL
  - from:
    - podSelector:
        matchLabels:
          {{- include "ccf-api.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: api
    ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
    to:
    - podSelector:
        matchLabels:
          {{- include "ccf-api.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: database
  
  # Allow external traffic to API
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
    to:
    - podSelector:
        matchLabels:
          {{- include "ccf-api.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: api
  
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
  
  # Allow API to connect to PostgreSQL
  - from:
    - podSelector:
        matchLabels:
          {{- include "ccf-api.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: api
    to:
    - podSelector:
        matchLabels:
          {{- include "ccf-api.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: database
    ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
  
  # Allow outbound HTTPS for external services
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
{{- end }}