{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ccf-api.fullname" . }}-api
  labels:
    {{- include "ccf-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ccf-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}