{{- if not .Values.externalSecrets.enabled }}
# Only create secrets if not using external secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-api.fullname" . }}-secrets
  labels:
    {{- include "ccf-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials
  database-password: {{ .Values.postgresql.auth.password | quote }}
  database-username: {{ .Values.postgresql.auth.username | quote }}
  database-name: {{ .Values.postgresql.auth.database | quote }}
  
  # JWT secrets
  jwt-secret: {{ .Values.api.auth.jwtSecret | default (randAlphaNum 32) | quote }}
  
  # API secrets
  {{- if .Values.api.auth.apiKey }}
  api-key: {{ .Values.api.auth.apiKey | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-api.fullname" . }}-postgresql
  labels:
    {{- include "ccf-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
{{- end }}