apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ccf-api-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/compliance-framework/configuration-service
    targetRevision: chore-kubernetes-deployment  # TODO: Change to main after merge
    path: helm-chart/ccf-api
    
    helm:
      valueFiles:
        - values-prod.yaml
      
      # Override to use external secrets
      parameters:
        - name: externalSecrets.enabled
          value: "true"
        - name: api.image.tag
          value: "v1.0.0"  # Use specific version tag
        - name: networkPolicy.enabled
          value: "true"
        - name: podDisruptionBudget.enabled
          value: "true"
        - name: autoscaling.enabled
          value: "true"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ccf-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Add health checks for sealed secrets
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  
  revisionHistoryLimit: 10